### ISSUE TITLE
Unclear error message when trying to login while not connected to internet

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#10]
When you try to login while not connected to the internet, the error message is not very helpful. There should be a clearer error message.

**Steps to reproduce:**
1. Disconnect from the internet.
2. Attempt to sign in. 

![image](https://user-images.githubusercontent.com/22312351/57647019-0e225580-7616-11e9-977b-a7ff175425c5.png)

**Comment by zeshili** [comment]
When I follow the steps to reproduce the error, I get a "No internet connection" error message instead.


<img width="409" alt="Screen Shot 2019-05-22 at 9 22 11 AM" src="https://user-images.githubusercontent.com/17919332/58191588-ba49e900-7c73-11e9-9590-890e0e916412.png">

**Comment by jbenning97** [comment]
Why do we get different errors for different OS?

Error message should include 'failure to login'

**Comment by ajlarivi** [comment]
I was able to reproduce the gross error message, running linux.

**Comment by aujlarj** [comment]
This issue is resolved. Code reviews done and pull request merged
