### ISSUE TITLE
failure to get remote repository using "origin/{branch-name}"

### ISSUE THREAD

**Issue by cchampernowne** [uvicgse/project-virtual-team-2#101]
remote repos not being recognized by visual git 

hard-coded fix on my machine worked using 
`return repo.getReferenceCommit("refs/remotes/origin/master").then(function (remoteCommit) `

instead of 
`return repo.getReferenceCommit(origin).then(function (remoteCommit) `
(git.ts, 979)

and 
`return repo.getBranch("refs/remotes/origin/master").then(function (originCommit)`

instead of
`return repo.getReferenceCommit(origin).then(function (originCommit)`
(git.ts, 997)

**Comment by aujlarj** [comment]
Fixed and merged. [See Pull request](https://github.com/uvicgse/project-virtual-team-2/pull/97)
