### ISSUE TITLE
browse and search existing tags

### ISSUE THREAD

**Issue by AhmadAlsaif** [uvicgse/project-virtual-team-2#106]
#### Feature request:
This is a decomposition of issue #40. The functionality required here should allow the user to:

1. browse all existing tags

2. search for a certain tag

**Comment by AhmadAlsaif** [comment]
Hey @jamshale, do we want to show all the tags and allow the user to search them in this list?

<img width="667" alt="Screen Shot 1440-10-11 at 8 36 07 PM" src="https://user-images.githubusercontent.com/39515277/59546551-51593800-8ee4-11e9-8274-7a47f2356fdf.png">

**Comment by jamshale** [comment]
Ya I think that's the best plan. Need to design it to separate branches and
tags. Maybe tabs like the other team did or some other way. We should be
able to use a bunch of that pre existing functionality
