### ISSUE TITLE
Move fetch button and change local status messge

### ISSUE THREAD

**Issue by ajlarivi** [uvicgse/project-virtual-team-2#107]
Continuation of #88, the following functionalities were requested:
- move the fetch button from the footer to the header
- change the text of the local status to indicate requiring a fetch in order to update with the remote
- make local status display both ahead and behind if local repo is both, instead of just behind

**Comment by aujlarj** [comment]
see [Pull Request](https://github.com/uvicgse/project-virtual-team-2/pull/116)
