### ISSUE TITLE
Pressing F5 resets the app

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#11]
Regardless of where you are within the app, pressing F5 resets the whole app and takes you back to the login screen. This should not be possible as it may produce unexpected behavior for the rest of the app and gives the impression the app is not stable.

**Steps to reproduce:**

1. Sign in or continue without sign in on Visual Git
2. Press F5
3. Observe app reset

**Expected Output:**

F5 no longer takes you back to the login screen

**Comment by zeshili** [comment]
From sprint planning meeting: F5 does nothing in the future.

**Comment by jbenning97** [comment]
Fixed in https://github.com/uvicgse/project-virtual-team-2/pull/49

**Comment by jbenning97** [comment]
Additional fixes in https://github.com/uvicgse/project-virtual-team-2/pull/59
