### ISSUE TITLE
Redesign branch dropdown and code refactor

### ISSUE THREAD

**Issue by jamshale** [uvicgse/project-virtual-team-2#118]
The existing branch dropdown had a quickly implemented design and codebase. It should be re-worked. 

The delete branch functionality was buggy and didn't work consistently.

Front-end UI:
![image](https://user-images.githubusercontent.com/31809382/59648304-70013e00-9133-11e9-8ee4-46bd701c54f2.png)

Code Snippet:

![image](https://user-images.githubusercontent.com/31809382/59648351-accd3500-9133-11e9-89e1-fc17d24b5223.png)

**Comment by jamshale** [comment]
Here is the update:

UI:
![image](https://user-images.githubusercontent.com/31809382/59648483-0897be00-9134-11e9-8549-434b5506e435.png)

Some code:

![image](https://user-images.githubusercontent.com/31809382/59648511-22d19c00-9134-11e9-914a-eca859a08894.png)

**Comment by AhmadAlsaif** [comment]
Fixed in PR #119
