### ISSUE TITLE
File editor overflows on certain resolutions

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#3]
**Steps to reproduce:**
1.Login into visual git
2.Clone a repo
3.Observe the file-editor on the left hand corner

Observed Behavior:
![image](https://user-images.githubusercontent.com/36385673/57414681-40663880-724d-11e9-8884-ce111f500266.png)

**Comment by AhmadAlsaif** [comment]
Hi @jtiz003, which design would you prefer?
Design 1: 
<img width="291" alt="Design1" src="https://user-images.githubusercontent.com/39515277/58693270-395eb180-8345-11e9-9980-d41d869cd054.png">

Design 2: 
<img width="324" alt="Design2" src="https://user-images.githubusercontent.com/39515277/58693336-6a3ee680-8345-11e9-884e-a552d95fb17e.png">
