### ISSUE TITLE
Add stashing and reapplying functionality

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#35]
Add support for stashing and reapplying changes, so that users can store their changes without committing and move on to another branch. The user should be able to view what changes are stashed on what branches

**Comment by mdesco18** [comment]
https://git-scm.com/docs/git-stash
https://www.nodegit.org/api/repository/
https://www.nodegit.org/api/stash/
https://www.nodegit.org/api/stash_apply_options/
https://github.com/nodegit/nodegit/blob/master/lib/stash.js

**Comment by mdesco18** [comment]
**Update**
Currently: Basic stashing is done but requires more testing. 
In progress: Make popping work properly
Next: Implement [options]

**Comment by mdesco18** [comment]
**Update**
Currently: Basic popping is done
In progress: finish testing popping
Next: implement drop and [options]. 

PR on track to be up by tomorrow evening

**Comment by mdesco18** [comment]
**Update**
Currently: functionality implemented and tested
In Progress: Implementing GUI components for issue
Next: Publish Pull Request

**Comment by mdesco18** [comment]
Update
Currently: GUI has been implemented and tested. Could use some css rework for when displaying multiple stashes
In progress: dropping functionality not working
Next: demo and renegotiate

**Comment by mdesco18** [comment]
Updates in #84
