### ISSUE TITLE
Redesign commit process with drag and drop feature 

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#39]
A redesign of the commit process involving dragging and dropping each individual file change to add them or remove them from each part of the process. This is as opposed to the current process of individually clicking on ones you want to keep. Each file change should be draggable and should have multiple ways of keeping or removing it from the actual commit.

**Comment by aujlarj** [comment]
Documentation and Research regarding Drag and Drop can be found [@here](https://github.com/uvicgse/project-virtual-team-2/wiki/Drag-and-Drop-Feature-Documentation)

**Comment by mdesco18** [comment]
Closed via #115

**Comment by aujlarj** [comment]
Enhancement to Drag and Drop UI added later. via ### pull request
