### ISSUE TITLE
Add tagging support

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#40]
**Feature request:**

Add support for tagging commits in the past and/or the current commit that has yet to be pushed. This will allow users to mark important points in their repository for example "v1.0" without needing to search for a certain commit message/checksum. Users should also be able to view the tags on the main page

**Comment by jtiz003** [comment]
From sprint 1 negotiation: This issues will be investigated in sprint 1, with the intention to complete it in sprint 2.

**Sprint 1 objectives:**
- Build knowledge of the relevant parts of the application.
- Have a clear plan of how to implement this. 
- Provide time estimates for the required work
- (Optional) Begin implementation.

**Comment by jtiz003** [comment]
@Zanelib1 Could you please document your research findings here. 
Thanks!

**Comment by csamcharles** [comment]
Hi @jtiz003,
 
[here is a link](https://github.com/uvicgse/project-virtual-team-2/blob/master/docs/tagging-support.md) to the doc I created for the research on tagging support. This may be reference for all during the tagging implementation in sprint 2.

**Comment by csamcharles** [comment]
**Update:** this issue as been broken into two smaller issues.

* [Issue #61: Modifying existing tags](https://github.com/uvicgse/project-virtual-team-2/issues/61)
* [Issue #62: Enabling viewing tags on mouse hover](https://github.com/uvicgse/project-virtual-team-2/issues/62)

Once those issues are resolved this issue will be updated accordingly. We may still want to add further functionality in tagging support - such as searching commits by tags. 

*Any further feature functionality will be carried over into sprint 3.*

**Comment by zeshili** [comment]
**Update**:
We have completed the following issues for sprint2:

- [Issue #82: Enable add tag when creating commit ](https://github.com/uvicgse/project-virtual-team-2/issues/82)

- [Issue #83: Add support for deleting tag ](https://github.com/uvicgse/project-virtual-team-2/issues/83)

**Comment by mdesco18** [comment]
Is this closed? If not, want to add documentation for future considerations?

**Comment by csamcharles** [comment]
This issue is closed, tagging support has been added.
