### ISSUE TITLE
Create a button modifying tags

### ISSUE THREAD

**Issue by HDeBoever** [uvicgse/project-virtual-team-2#61]
New Feature: 

As per the reasearch that group 6 has done, there is a need for a front end component in order to incorporate some tagging functionality. The button could be located on the top taskbar and its features could be implemented from a drop down menu located there on button-click.

The button would open a window where the user could type the branch name, and the tag. Once a user enters a valid tag name, the tag attribute would be associated with the specified branch.

**Comment by zeshili** [comment]
This issue was resolved by pull request #100
