### ISSUE TITLE
CommitButNoPush variable gets reset to 0 when reloading app

### ISSUE THREAD

**Issue by smithmr** [uvicgse/project-virtual-team-2#63]
## Problem
When I commit and then reload the application I can no longer push.

## steps to reproduce
1. Commit changes
2. reload the app
3. try and push

## suggested fix
- ensure CommitButNoPush variable is set appropriately when restarting the app.

**Comment by Leon0315** [comment]
<img width="356" alt="Screen Shot 2019-06-01 at 2 55 41 PM" src="https://user-images.githubusercontent.com/15313467/58754019-55656e80-847d-11e9-91cc-a205e7b83f92.png">
This pops up when trying to reload with unpushed commits, so there's already a warning telling users to save(push) everything before reload.
