### ISSUE TITLE
2nd push causing crashes

### ISSUE THREAD

**Issue by smithmr** [uvicgse/project-virtual-team-2#64]
2nd time pushing is causing app to crash

## steps to reproduce
1. commit
2. push
3. commit
4. push

## suggested fix
The issue has something to do with authentication

**Comment by Leon0315** [comment]
Found this issue https://github.com/nodegit/nodegit/issues/982 form nodegit. The user credentials are somehow not read properly after first commit and push

**Comment by Leon0315** [comment]
<img width="383" alt="Screen Shot 2019-06-02 at 12 36 35 PM" src="https://user-images.githubusercontent.com/15313467/58766412-1134a580-8533-11e9-816b-21cd7c641cdb.png">

This is the `cred` with normal behavior, but the `Cred` object will become undefined if trying to push the second time, not sure why, but the solution is to have a fresh copy of `cred` every time when required
