### ISSUE TITLE
Feature request: Show most recent repositories

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#7]
Implement a feature into VisualGit which shows the users most recent (maybe recent 5?) opened repositories, and lets them open them.

**Comment by Leon0315** [comment]
<img width="1040" alt="Screen Shot 2019-05-22 at 3 56 56 PM" src="https://user-images.githubusercontent.com/15313467/58214352-3c550480-7caa-11e9-95f7-9d63a0881a34.png">
It should show on this page

**Comment by jbenning97** [comment]
Merged in https://github.com/uvicgse/project-virtual-team-2/pull/50
