### ISSUE TITLE
Clicking 'Sign in' Button After Continuing Without Signing In

### ISSUE THREAD

**Issue by jbenning97** [uvicgse/project-virtual-team-2#72]
## Steps to reproduce

1. Open app
2. Click 'Continue without sign in' button
3. Click 'Sign in button'

<img width="1274" alt="Screen Shot 2019-06-03 at 9 36 48 PM" src="https://user-images.githubusercontent.com/19715502/58851565-1fc0b100-8648-11e9-9b2e-e0ba9aa5e8b4.png">

## Suggested Fix
Rework the input element container to fit inside of the navbar, and also center the 'Sign in' button vertically in navbar

**Comment by mdesco18** [comment]
Fixed by #20

**Comment by mdesco18** [comment]
closed via #136
