### ISSUE TITLE
Making a commit through visual git does not cause the graph to update

### ISSUE THREAD

**Issue by ovrynn** [uvicgse/project-virtual-team-2#8]
Making a commit through visual git does not cause the graph to update.

**Steps to reproduce:**

1. Make local changes
2. Stage and commit the changes.

**Actual behavior:** Node graph doesn't update

**Expected behavior:** Node graph should now contain the new commit

**Comment by jbenning97** [comment]
Fixed in https://github.com/uvicgse/project-virtual-team-2/pull/52
