### ISSUE TITLE
Upgrade Electron and Node version

### ISSUE THREAD

**Issue by Leon0315** [uvicgse/project-virtual-team-2#99]
There's a need to use a more up-to-date version of Electron and Node.js in order to authenticate Github users through Oauth method. Might also need to fix issue #25 together as well.

**Comment by Leon0315** [comment]
Fixing this issue will also fix #20, as the current electron build-in browser won't let us authenticate users. @c-renard @katland @aujlarj

**Comment by Leon0315** [comment]
when upgrading to electron 5.0.3 directly from 1.2.8, got errors on the console panel. Will try to upgrade version by version.
<img width="520" alt="Screen Shot 2019-06-10 at 12 28 23 PM" src="https://user-images.githubusercontent.com/15313467/59230618-e087e800-8b92-11e9-9346-9f20cbc127f9.png">

**Comment by c-renard** [comment]
@Leon0315 I have created a new branch specifically for fixing this issue, it is just called issue99

**Comment by katland** [comment]
Upgrading to the next version (1.2.8 to 1.3) also creates errors, for example:
![Screen Shot 2019-06-11 at 9 29 57 AM](https://user-images.githubusercontent.com/10343127/59289724-a0c10f00-8c2b-11e9-94bc-1008ad47dd5e.png)

**Comment by smithmr** [comment]
@Leon0315 The issue is because electron requires you specify the node integration.

https://github.com/SimulatedGREG/electron-vue/issues/644

That should fix it..
